main/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
        path('', views.index, name='index'),
        path('about/', views.about, name='about'),
        path('download/', views.download, name='download'),
        path('run/', views.run_pipeline, name='run'),
        path('report/', views.report, name='report'),
]

video_upload/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('generate/', include('main.urls'))
]

main/forms.py
from django import forms

from main.models import UserPhoto


class CoverForm(forms.ModelForm):
    BACKGROUND_CHOICES = (
        ("generate_bg", "Сгенерировать фон"),
        ("use_frames", "Использовать кадры из видео"),
    )
    TEXT_CHOICES = (
        ("red", "Красный"),
        ("white", "Светлый"),
        ("yellow", "Яркий")
    )
    COVER_STYLE_CHOICES = (
        ("no_style", "Без стиля"),
        ("anime_style", "Аниме"),
    )

    background_type = forms.ChoiceField(
        label="Тип фона",
        widget=forms.Select(attrs={"class": "form-control"}),
        initial="generate_bg",
        choices=BACKGROUND_CHOICES,
        required=True
    )

    description_text = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control', 'rows': 5, 'cols': 40,
        }),
        label="Текстовое сопровождение",
        required=True
    )

    text_decor = forms.ChoiceField(
        label="Оформление текста",
        widget=forms.Select(attrs={"class": "form-control"}),
        initial="white",
        choices=TEXT_CHOICES,
        required=True
    )

    face_picture = forms.ImageField(
        label='Выберите фото для загрузки',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'file-upload btn btn-primary',
            }),
        required=False
    )

    class Meta:
        model = UserPhoto
        fields = ['face_picture', 'description_text', 'text_decor', 'background_type']

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-3 text-center">
            <img src="{% static 'ph/ph_vadim.jpg' %}" alt="Description" class="img-fluid">
            <p class="font-weight-bold">Вадим Шабашов <br> Machine Learning Engineer</p>
        </div>
        <div class="col-md-3 text-center">
            <img src="{% static 'ph/ph_elisey.jpg' %}" alt="Description" class="img-fluid">
            <p class="font-weight-bold">Елисей Евсеев <br> Machine Learning Engineer</p>
        </div>
        <div class="col-md-3 text-center">
            <img src="{% static 'ph/ph_anvar.jpg' %}" alt="Description" class="img-fluid">
            <p class="font-weight-bold">Анвар Тлямов <br> Data Scientist</p>
        </div>
        <div class="col-md-3 text-center">
            <img src="{% static 'ph/ph_dmitry.jpg' %}" alt="Description" class="img-fluid">
            <p class="font-weight-bold">Дмитрий Сайфулин <br> Data Engineer</p>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-12">
            <p class="font-weight-bold">Команда CatWorker$</p> была создана в марте 2022 студентами корпоративной магистратуры ИТМО
            "Разработка программного обеспечения". С самого начала учебы мы сработались как команда
            и выполняли групповые проекты вместе. Сейчас мы пробуем свои силы в хакатонах, знаем сильные
            и слабые стороны друг друга, организуя dream-team.
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {# src files for styling #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/css/material-fullpalette.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/css/material.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/css/ripples.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/css/roboto.css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/js/material.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/js/ripples.js'></script>


    <title>Cover Crafter </title>

    <link rel="stylesheet" href="{% static 'css/app.css' %}?{% now "U" %}">
  </head>

  <body>
{#    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #000000;">#}
    <nav class="navbar navbar-expand-lg navbar-dark">
{#      <a class="navbar-brand" href="#">Navbar</a>#}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="/static/logo/cat.png" width="80" height="80" alt="">
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if navbar == 'generate' %} active {% endif %}"
               href="{% url 'index' %}">
                Сгенерировать обложку <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if navbar == 'about' %} active {% endif %}"
               href="{% url 'about' %}">
                О нас <span class="sr-only">(current)</span></a>
          </li>

        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link {% if navbar == 'report' %} active {% endif %}"
               href="{% url 'report' %}">
                Bug report <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="main_content">
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="col-lg-6 col-md-6" style="margin: 40px auto; display: block;">
    <form enctype="multipart/form-data" method="POST" action="" style="text-align: center;" id="video_form">
        {% csrf_token %}

        <div><label for="video_upload" class="form-label">Выберите видео для загрузки</label></div>
        <div class="file-upload btn btn-primary">
            <span>ВЫБРАТЬ ФАЙЛ</span>
            <input type="file" name="file attachment" class="upload" id="video_upload"/>
        </div>

        <button type="submit" id="submit" class="btn btn-primary" name="submit_video_form">ЗАГРУЗИТЬ ВИДЕО</button>
    </form>

    <form method="post" enctype="multipart/form-data" action="" style="text-align: center;" id="cover_options_form">
        {% csrf_token %}

        <div><label for="video_upload" class="form-label">Выберите фото пользователя</label></div>
        <div class="file-upload btn btn-primary">
            <span>ВЫБРАТЬ ФАЙЛ</span>
            <input type="file" name="face_picture" class="upload" id="id_face_picture"/>
        </div>

        {% for field in cover_options_form %}
            {% if not field.name == "face_picture" %}
                <p>{{ field.label_tag }} {{ field }}</p>
            {% endif %}
        {% endfor %}

        <button type="submit" class="btn btn-primary" name="submit_cover_options_form">ОТПРАВИТЬ ПАРАМЕТРЫ</button>
    </form>

    {# progress bar #}
    <div id="uploaded_files"></div>

    {# spinner and running pipeline #}
    <div id="run_pipeline" hidden class="run_pipeline text-center">
        {# кнопка #}
        <a id="run_button" href="{% url 'run' %}" class="btn btn-primary">ГЕНЕРИРОВАТЬ</a>
        <div class="d-flex justify-content-center">
            <button id="spinner-box"
                    class="btn btn-primary btn-convert"
                    type="button"
                    hidden disabled>
                <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                Обработка...
            </button>
        </div>
    </div>

    {# result cover #}
    <div id="result_file" class="text-center" hidden>
        <a href="{% url 'download' %}" class="btn btn-primary" id="pass_file">СОХРАНИТЬ ОБЛОЖКУ</a>
    </div>


</div>

{% endblock %}

templates/report.html
{% extends 'base.html' %}

{% block content %}
<div class="report-block d-flex justify-content-center">
{#    <p class="inside-text">#}
{#    <strong>Нашли ошибку? Напишите нам</strong>#}
{#    </p>#}
    <form class="needs-validation" novalidate>
      <div class="form-row">
        <div class="col-md-4 mb-3">
          <label for="validationCustom01">Имя</label>
          <input type="text" class="form-control" id="validationCustom01" placeholder="Имя" required>
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-md-4 mb-3">
          <label for="validationCustom02">Фамилия</label>
          <input type="text" class="form-control" id="validationCustom02" placeholder="Фамилия" required>
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-md-4 mb-3">
          <label for="validationCustomUsername">Email</label>
          <div class="input-group">
            <input type="text" class="form-control" id="validationCustomUsername" placeholder="Email" aria-describedby="inputGroupPrepend" required>
            <div class="invalid-feedback">
              Пожалуйста, укажите email.
            </div>
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-3 mb-3">
          <label for="validationCustom03">Страна</label>
          <input type="text" class="form-control" id="validationCustom03" placeholder="Страна" required>
          <div class="invalid-feedback">
            Укажите страну.
          </div>
        </div>
        <div class="col-md-3 mb-3">
          <label for="validationCustom04">Город</label>
          <input type="text" class="form-control" id="validationCustom04" placeholder="Город" required>
          <div class="invalid-feedback">
            Укажите город.
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-10 mb-4">
          <label for="validationCustom03">Что произошло?</label>
          <input type="text" class="form-control" id="validationCustom03" placeholder="Обнаружена следующая ошибка..." required>
          <div class="invalid-feedback">
            Укажите причину обращения.
          </div>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
          <label class="form-check-label" for="invalidCheck">
            Соглашаюсь с правилами и условиями
          </label>
          <div class="invalid-feedback">
            You must agree before submitting.
          </div>
        </div>
      </div>
      <button class="btn btn-primary" type="submit">Отправить</button>
    </form>
</div>

{% endblock %}